### ISSUE TITLE
Is there a way to use sacremoses in java?

### ISSUE THREAD

**Issue by SefaZeng** [alvations/sacremoses#123]
I wanna deploy my to model to android device, so I need to do some preprocess for the raw text. But I can't find a replacement for sacremoses on java.

**Comment by alvations** [comment]
There should be ways to run Python in Java. https://www.baeldung.com/java-working-with-python 
But this isn't natively support by sacremoses. 

If there's more interests in porting these to more languages, there can be effort put in but for now, no plans to support anything beyond Python (and maybe C++).
