### ISSUE TITLE
Which of the 100 languages used in mBERT are not supported by this tokenizer?

### ISSUE THREAD

**Issue by fake-warrior8** [alvations/sacremoses#125]
Hi, I'd like to know what are the general languages supported by this tokenizer tool.  Is this tokenizer tool  compatible with the 100 languages used by mBERT or XLM-R? I know that some languages such as Chinese and Thai require some additional word segmentation preprocessing for raw texts. So, are there any other languages out of those 100 languages that require additional preporcessing beyond this tokenizer tool?

**Comment by alvations** [comment]
I think it's easier to ask the mBERT or XLM-R creators which ones they use. Hope I can help more.
