### ISSUE TITLE
distutils is deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [alvations/sacremoses#126]
https://www.python.org/dev/peps/pep-0632/#migration-advice . Since setuptools is available using `setup` from setuptools will fix this.

https://github.com/alvations/sacremoses/blob/9807459206c0a7c9009124596ded003e4262a0fc/setup.py#L1

**Comment by alvations** [comment]
Thanks for raising the issue! The new version should fix it.
