### ISSUE TITLE
Loading existing truecase models is broken

### ISSUE THREAD

**Issue by Patdue** [alvations/sacremoses#18]
observed counts should be casted to int for the `_casing_to_model` method to work.

```python
casing[token.lower()][token] = int(count)
```
Else, the counter sorting is done lexically, resulting in counts with less digits than the second highest count to be set as `best`, e.g. `"400"<"40"`

**Comment by alvations** [comment]
Loading since the new v0.07 interface should work now. Please re-open this issue if there's still any issues.
