### ISSUE TITLE
Generic apostroph is not correctly tokenized 

### ISSUE THREAD

**Issue by Patdue** [alvations/sacremoses#19]
The apostroph is not correctly tokenized for other languages than english, french and italian.

Problem is line 171 in `tokenize.py` 
```
NON_SPECIFIC_APOSTROPHE = r"\'", r" \' "
```
The second apostophe must not be escaped, because the backslash in the substitution is read as literal character and not as an escape character. The first backlash is not nessecary.

```
NON_SPECIFIC_APOSTROPHE = r"'", " ' "
```

should work.

**Comment by alvations** [comment]
Thanks @Patdue! Patched in #40
