### ISSUE TITLE
Is is_lower() a typo for islower() in truecase.py?

### ISSUE THREAD

**Issue by michaele4321** [alvations/sacremoses#34]
When I try to call MosesTruecaser().train with possibly_use_first_token=True I get this error:
`AttributeError: 'str' object has no attribute 'is_lower'`
for line 103 in truecase.py which is:
`if token[0].is_lower():`

Either token[0] is not intended to be of type str  - or `is_lower() `should be `islower()`

**Comment by alvations** [comment]
Good catch! Yes, I was mixing syntax between perl and python. It should be `islower()`

**Comment by alvations** [comment]
Thanks again @michaele4321! Patch in 926c68a130287bfa840d930602714e4908218b2d, should be working now.
