### ISSUE TITLE
Flag --protected from original Moses tokenizer

### ISSUE THREAD

**Issue by noe** [alvations/sacremoses#35]
The [original Moses tokenizer](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl) supports the `--protected` flag. It's effect is to accept a file with a list of regular expression that should be _protected_ from tokenization.

Under the hoods, the tokenizer masks each match of the regexes, then tokenizes, then unmasks.

Is this functionality in the roadmap of sacremoses?

**Comment by alvations** [comment]
Hmmm, looks easy to implement but tricky to test. 

Do you have any example `protected_patterns_file` and related text that contains those patterns that can be tested? If you do, then I could easy code it up and write the test =)

**Comment by noe** [comment]
Sorry, I don't have an example of such files. My intention was to avoid URLs being tokenized and I was planning to use a regex like this one:

```
    import re
    regex = re.compile(
        r'(?:http|ftp)s?://'  # http:// or https://
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?))'
        r'(?::\d+)?'  # optional port
        r'(?:/\w+)*'
        r'(?:(?:\.[a-z]+)|/?)', re.IGNORECASE)
```
Then I found out that Moses tokenizer supported it and checked sacremoses for it because it's what we use.

P.S.: this is in our code but I don't know where I took it from; my past self wrote as a comment that it's loosely based on [Django's URL validators](https://github.com/django/django/blob/master/django/core/validators.py) but my present self can't see an evident connection with it.

**Comment by alvations** [comment]
@noe Django URL validators is a little too heavy to incorporate here. 

I've tried incorporating the `protected_patterns` feature from https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/basic-protected-patterns and a test case against the pattern you've listed in the previous comment in #46

**Comment by alvations** [comment]
Added feature. Thanks again @noe ! c.f. #46

**Comment by ganeshvictory** [comment]
Hi @alvations , the above code snippet is just handling the case if there are string before and after the url and in fact it is taking the url only in specific format. So my question is if there's any way that it can handle any condition say like even if the text has only url it shouldn't tokenise or in some cases even if there's no text before or after the url?

Thanks in advance!
