### ISSUE TITLE
Class issue for Python2

### ISSUE THREAD

**Issue by keon** [alvations/sacremoses#4]
@alvations 
pytorch/text (torchtext) library is looking to migrate to sacremoses
but we are experiencing following error.

https://travis-ci.org/pytorch/text/jobs/387871950

**Comment by alvations** [comment]
Ah, the old `super()` haunts again. 

I'm reluctant to change [this line](class MosesTokenizer(object):) to old style import with explicit superclass but I guess that's the only way for Python2.7.9.final to accept the super init.... 

Changing it right away =)

**Comment by alvations** [comment]
@keon Thanks for notifying on this! The change is done, tell me if the Travis on `pytorch/text` still fails.
