### ISSUE TITLE
Truecaser Test dependency on norvig.com/big.txt

### ISSUE THREAD

**Issue by DavidHarrison** [alvations/sacremoses#49]
norvig.com is currently down which is causing the tests in `sacremoses/test/test_truecaser.py` to fail if `big.txt` has not already been downloaded. I'm wondering if there is another source of the file that might be more reliable or whether it could be included in the repository (e.g. with Git LFS).

**Comment by alvations** [comment]
Thanks @DavidHarrison for the suggestion! I wanted to keep the testing light so I left out the file rather than putting it in the repo with LFS.

I'll try to look out for better way(s) to test file in, file out functions. That'll be helpful for #37 too.

**Comment by alvations** [comment]
I've created a "mirror" of the https://norvig.com/big.txt on https://gist.githubusercontent.com/alvations/6e878bab0eda2624167aa7ec13fc3e94/raw/4fb3bac1da1ba7a172ff1936e96bee3bc8892931/big.txt 

That should work as a backup =)

**Comment by alvations** [comment]
Resolved c.f. #59
