### ISSUE TITLE
Issue in handles_nonbreaking_prefixes

### ISSUE THREAD

**Issue by Patdue** [alvations/sacremoses#51]
There is an issue in `handles_nonbreaking_prefixes`, more specifically on line `271`, where you check if the next token is all lowercase. 

The original perl script just checks if the first character of the next token is lowercase. (as stated here: https://stackoverflow.com/questions/42126922/what-does-pre-pre-pisalpha-mean-in-the-moses-tokenizer)

So for example `4.5.1. dist-upgrade schlägt fehl mit` is detokenized to `4.5.1 . dist-upgrade schlägt fehl mit` because the hyphen is not in the list of lower case characters.

**Comment by Patdue** [comment]
To stay close to the original perl implementation i would change the `is_lower` method  to `is_first_lower`:

```python
    def is_first_lower(self, text):
        return re.match(r"^[{islower}]".format(islower=self.IsLower), text)
```

**Comment by alvations** [comment]
@Patdue Thanks for catching this! 

The notion of Perl's "is first lower" (aka `ucfirst`) is kind of strange. I sat thinking about this for a while before, "what are cases where first is not lower but there are upper cases in the text?". 

Perhaps, this be a better `is_first_lower`:


```python
def is_first_lower(self, text):
    return text[0].islower()
```

**Comment by Patdue** [comment]
In my opinion `(i != num_tokens - 1 and self.islower(tokens[i + 1][0]))):` is much more pythonic and should work just as expected.
We just need to be sure that there are no empty tokens so there are no `IndexError`s.

**Comment by alvations** [comment]
Adding a check for nully string should work =)

```
(i != num_tokens - 1 and tokens[i+1] and self.islower(tokens[i + 1][0]))
```

**Comment by alvations** [comment]
Resolved c.f. #59
