### ISSUE TITLE
Comma after a number at the end of the sentence not split

### ISSUE THREAD

**Issue by Patdue** [alvations/sacremoses#52]
Commas after numbers at the end of a sentence are not split away, but they should be.
For example in `Sicherung dieser Daten erstellen ( wie unter Abschnitt 4.1.1,`  the last comma should be split away.

The third comma rule of the original perl script (Line `298`) is missing in this implementation.

Fix:
On line `60` in `tokenize.py`
```python
    COMMA_SEPARATE_3 = u'([{}])[,]$'.format(IsN), r'\1 , '
```
On line `349` add the rule: 

```python
        for regexp, substitution in [self.COMMA_SEPARATE_1, self.COMMA_SEPARATE_2, self.COMMA_SEPARATE_3]:
            text = re.sub(regexp, substitution, text)
```

**Comment by alvations** [comment]
Patch via #54

**Comment by alvations** [comment]
Thanks @Patdue for catching it and giving the solution!!
