### ISSUE TITLE
Truecaser for foreign languages!

### ISSUE THREAD

**Issue by gvskalyan** [alvations/sacremoses#68]
Can the train-truecaser can be applied to any txt file containing foreign characters i.e., for foreign language truecasing such as german/spanish etc..
`
        # Some predefined words that will always be in lowercase.
        self.ALWAYS_LOWER =
`

Due to such blocks in the code?

**Comment by alvations** [comment]
@gvskalyan yes the truecasing can be trained for any languages (mostly people use it for European languages).

As for the code you've mentioned, it's from https://github.com/alvations/sacremoses/blob/master/sacremoses/truecase.py#L457 which is actually only used during detruecasing (not training) and also normally would never be activated unless you turn on `is_headline=True` (default it's off).

**Comment by gvskalyan** [comment]
can this also be used for CJK unicode characters truecasing?

**Comment by alvations** [comment]
CJK doesn't have case ;P

```python
>>> x = "巴西北部的帕拉州當前下轄144個市鎮。"
>>> x[0].isupper()
False
>>> x[0].islower()
False
```

A truecase model can still be trained and used, so as to have a consistent pre-/postprocessing pipeline but it'll have no effect.

**Comment by gvskalyan** [comment]
https://github.com/alvations/sacremoses/blame/master/README.md#L69 - Should mosestokenizer be applied to sentence before truecasing it since while training the model all sentences are tokenized and then learnt.

**Comment by alvations** [comment]
Usually people tokenize before truecasing
