### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by noqcks** [alvations/sacremoses#83]
It would be nice to have a LICENSE file, so automatic parsers can read it

Thank you

**Comment by alvations** [comment]
Ah that was left out on purpose. But let me try the attempt again at moving this away from LGPL to MIT/Apache

It's a little complicated because the original Moses is LGPL.

**Comment by chen955** [comment]
Can you help upload the LICENSE file?

Thank you

**Comment by alvations** [comment]
Please see #93

**Comment by alvations** [comment]
License added #93. Thanks @chen955 for raising the issue!!
