### ISSUE TITLE
Non-breaking prefixes at the end of the sentence

### ISSUE THREAD

**Issue by ZJaume** [alvations/sacremoses#97]
I think Sacremoses tokenizer is not behaving like Moses tokenizer with the non-breaking prefixes when they end a sentence.

```
$ echo "John vs. Doe, says vs." | tokenizer.perl -q -l en
John vs. Doe , says vs .
$ echo "John vs. Doe, says vs." | sacremoses -l en tokenize
John vs. Doe , says vs.
```

**Comment by alvations** [comment]
This is the same issue as #21 where there's a difference kept on purpose. We've to see how to resolve this in a smarter way.

**Comment by ZJaume** [comment]
Sorry I didn't know the ohter issue was about non-breaking prefixes, closing.
